stages:
  - lint

lint_js:
  stage: lint
  image: node:14  # Use the Node.js Docker image with a specific version (e.g., Node.js 14)
  script:
    - npm install -g eslint  # Install ESLint globally (if not already installed)
    - eslint /src/js/*.js   # Use ESLint to check JavaScript files in /src/js/
  only:
    changes:
      - '/src/js/*'
