stages:
  - lint

lint_js:
  stage: lint
  script:
    - npm install -g eslint  # Install ESLint globally (if not already installed)
    - eslint /src/js/*.js   # Use ESLint to check JavaScript files in /src/js/
  only:
    changes:
      - '/src/js/*'         # Trigger the job when JavaScript files in /src/js/ change
  except:
    - schedules             # Exclude this job from scheduled pipelines
