name: Build & publish to github releases

on:
  push:
    branches: [work/raifcoonjah/automation/build-extention]

  pull_request:
    branches: [work/raifcoonjah/automation/build-extention]

# Jobs
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install web-ext using npm
        run: npm -g install web-ext
      - name: Install minify
        run: sudo apt install minify
      - name: Minify index.html
        run: minify -o index.html index.html
      - name: Minify css files
        run: |
          cd css
          minify -o anim.css anim.css
          minify -o core.css core.css
          minify -o custom.css custom.css
          minify -o styles.css styles.css
          minify -o themes.css themes.css
          cd ..
      - name: Minify JS files
        run: |
          cd js 
          minify -o favorites.js favorites.js
          minify -o focus.js focus.js
          minify -o index.js index.js 
          minify -o keyboard.js keyboard.js 
          minify -o quote.js quote.js 
          minify -o render.js render.js 
          minify -o search.js search.js
          minify -o themes.js themes.js
          cd ..
