name: Build & publish to github releases

on:
  push:
    branches: [work/raifcoonjah/automation/build-extention]

  pull_request:
    branches: [work/raifcoonjah/automation/build-extention]

# Jobs
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install web-ext using npm
        run: npm -g install web-ext
      - name: Install minify dependencies
        run: sudo apt install composer -y
      - name: Clone minify
        run: git clone https://github.com/mrclay/minify.git min && cd min
      - name: Composer install
        run: composer install --no-dev
      - name: Run minify on index.html
        run: minify --type=html -o index.html index.html
      - name: (Test) Cat file
        run: cat index.html

